[package]
name = "scop"
version = "0.1.0"
edition = "2021"
authors = ["Tom Sorabella <tsorabel@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obj_parser = { path = "./obj_parser"}
glfw = "*"
